<?php
return [
    'informix' => [
        'driver'          => 'informix',
        'host'            => env('IFX_HOST', 'localhost'),
        'database'        => env('IFX_DATABASE', 'forge'),
        'username'        => env('IFX_USERNAME', 'forge'),
        'password'        => env('IFX_PASSWORD', ''),
        'service'         => env('IFX_SERVICE', '11143'),
        'server'          => env('IFX_SERVER', ''),
        'db_locale'       => 'en_US.819',
        'client_locale'   => 'en_US.819',
        // 'db_encoding'     => 'GBK',
        'db_encoding'   => 'ISO-8859-1',
        'initSqls'        => false,
        'client_encoding' => 'UTF-8',
        'prefix'          => '',
    ],
    'ibg_100_7' => [
        'driver'          => 'informix',
        'host'            => env('IBG_100_7_HOST', 'localhost'),
        'database'        => env('IBG_100_7_DATABASE', 'forge'),
        'username'        => env('IBG_100_7_USERNAME', 'forge'),
        'password'        => env('IBG_100_7_PASSWORD', ''),
        'service'         => env('IBG_100_7_SERVICE', '11143'),
        'server'          => env('IBG_100_7_SERVER', ''),
        'db_locale'       => 'en_US.819',
        'client_locale'   => 'en_US.819',
        // 'db_encoding'     => 'GBK',
        'db_encoding'   => 'ISO-8859-1',
        'initSqls'        => false,
        'client_encoding' => 'UTF-8',
        'prefix'          => '',
    ],
];
